import Head from "next/head";
import { useEffect, useState } from "react";
import { UICore } from "../components";
import DynamicForm from "../components/dynamic_form";

let data = {
  name: "Tax Returns",
  published: false,
  logo_url:
    "https://avatars.slack-edge.com/2020-07-23/1272247436353_793a149f241acbdfde89_512.png",
  header_foreground: "#fff",
  header_background: "#131515",
  body_foreground: "#fff",
  body_background: "#2b2c28",
  controls_foreground: "#111",
  controls_background: "#D6FB00",
  page_background: "#fffafb",
  fields: [
    {
      id: "TsNEo2jmwE_x",
      name: "number_Ye-cGWor",
      label: "Number",
      min: 0,
      max: 10000,
      required: true,
      field_type: "NUMBER",
    },
    {
      id: "J3GzytUSnP3s",
      name: "long-text_Z8uaBJES",
      label: "Long Answer",
      placeholder: "help",
      required: false,
      field_type: "LONG_ANSWER",
    },
    {
      id: "r2kR2Vcblvvg",
      name: "select_3Gg-XNXS",
      label: "Select",
      options: [
        {
          value: "eg option 1",
        },
        {
          value: "eg option 2",
        },
      ],
      required: false,
      field_type: "CHECKBOX_GROUP",
    },
  ],
};

export default function Preview() {
  let previewSchema = null;
  useEffect(() => {
    window?.addEventListener(
      "message",
      (event) => {
        if (event.origin !== "http://localhost:3001") {
          return;
        }
        localStorage.setItem("previewData", event.data);
      },
      false
    );
  }, []);

  if (typeof window !== "undefined") {
    previewSchema = localStorage.getItem("previewData");
    console.log(previewSchema);
  }

  return (
    <UICore.Page>
      <Head>
        <title>{JSON.parse(previewSchema)?.name || "Lyreform"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UICore.Flex justify="center">
        {JSON.parse(previewSchema) ? (
          <DynamicForm data={JSON.parse(previewSchema)} />
        ) : (
          "loading..."
        )}
      </UICore.Flex>
    </UICore.Page>
  );
}
